{% set name = "minifi" %}
{% set version = "0.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}dev{{ GIT_DESCRIBE_NUMBER }}

source:
  folder: src
  git_url: ../

build:
  number: 0
  skip: true  # [win]
  run_exports:
    # Symbols are removed from a minor release to the next.
    # https://abi-laboratory.pro/index.php?view=timeline&l=rocksdb
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - automake
    - bison
    - cmake >=3.5.1,<4
    - flex
    - ninja >=1.10,<2
    - patch
    - pkgconfig
  host:
    - civetweb
    - cxxopts
    #- flex
    - gsl-lite
    - libarchive >=3.3.2,<4
    # libcoap  missing on conda-forge
    - libcurl
    - librdkafka
    - libsodium
    - libssh2
    - libxml2
      #- nettle
      #- open62541  minifi is outdated
    - python
    - rapidjson
    - rocksdb
    - yaml-cpp
    - zlib
  run:
    - cffi

test:
  imports:
    - minifi
  commands:
    - minifi.sh start
    - minifi.sh stop
    - minificontroller --help

about:
  home: https://nifi.apache.org/minifi
  license: Apache-2.0
  license_file: src/LICENSE
  summary: MiNiFi C++ is a complementatry data collection approach of the core tenants of NiFi.

  dev_url: https://github.com/apache/nifi-minifi-cpp

extra:
  recipe-maintainers:
    - sodre
